### ISSUE TITLE
DSDcc block functionality.

### ISSUE THREAD

**Issue by ncreddy2001** [argilo/gr-dsdcc#1]
I was previously working with gr-DSD block for decoding the audio and data from the NXDN I/Q samples i have recently moved from gnuradio 3.8 to 3.11 as gr-dsd block is not supported in 3.11 i have installed this block and replaced DSD block with this DSDcc block but was not able to get the audio output from the block, the block gave the fallowing output messages, please can you help me with the fallowing.

```
DSDNXDN::init: entering sync state
DSDNXDN::processFSW: sync lost (end)
DSDNXDN::init: entering sync state
DSDNXDN::processLICH: parity error
DSDNXDN::processLICH: rfChannelCode: 0 fnChannelCode: 0 optionCode: 3 direction: 1 parity: 1 m_lichEvenParity: 3
DSDNXDN::processFSW: match late +1
DSDNXDN::SACCH::decode: bad CRC
DSDNXDN::FACCH1::decode: bad CRC
DSDNXDN::processFSW: sync lost (end)

```

**Comment by argilo** [comment]
gr-dsd is just a thin wrapper around [DSDcc](https://github.com/f4exb/dsdcc), which does all the demodulation. I'd suggest asking about this problem there.

> gr-dsd block is not supported in 3.11

gr-dsd should work fine, including with GNU Radio's `main` branch.

**Comment by argilo** [comment]
I'll close off this issue for now, since it appears to be a problem with the underlying DSDcc.
