### ISSUE TITLE
No sound when running gr-dsdcc

### ISSUE THREAD

**Issue by iman432** [argilo/gr-dsdcc#3]
Hi,

I complied and installed gr-dsdcc(also DSDcc and mbelib ) and example grc is loaded successfully. i just changed RTL to USRP for working with my SDR,but when running example grc there is no any sound but radio signals are receiving based on graph.its worth to say with another grc can get analog radios and sound is normal.  i also attach my grc, its appreciated to share your opinion if something is wrong.
[USRP dsdcc.zip](https://github.com/argilo/gr-dsdcc/files/15299485/USRP.dsdcc.zip)

**Comment by argilo** [comment]
The flow graph works for me. The only error I noticed is that the USRP source's frequency should be set to `freq - offset` rather than `freq`, to compensate for the 100 kHz offset applied in the Frequency Xlating FIR Filter block.

**Comment by iman432** [comment]
Thanks for your response.
I also changed freq - offset but still no sound in output.

**Comment by argilo** [comment]
Frequency error can be a problem. Make sure the demodulated FM signal is centered at 0 Hz hen receiving a signal. You may need to adjust your receive frequency by a few hundred Hz.

Also, dsdcc is not perfect and can't demodulate all digital signals. It worked for a nearby DMR signal when I last tested it.
